---
title: "DE_Milo_Tissue_Myeloid Network expansion"
author: "Bidossessi Hounkpe"
date: "16/04/2023"
format: html
editor: visual
---

## Load data

```{r}
rm(list=ls())

load(file = "G:/My Drive/Projects/SCVI_Results/Immune_compartment_PBMC/Subset_Agosto_2023/Milo/individual_disease_nhoo/PBMC_Myeloid_session.RData")
```

```{r}

rm(list = as.vector(lsf.str())) #remove functions from global env
```

## Plot

```{r}
pacman::p_load(
  tidyverse,
  OmnipathR,
  igraph,
  ggraph,
  graphlayouts,
  ggforce,
  tidygraph,
  httr,
  SingleCellExperiment,
  scran,
  scuttle,
  ggprism,
  ComplexHeatmap,
  pheatmap,
  circlize,
  reticulate,
  RCy3,
  biomaRt,
  ghql,
  jsonlite,
  ktplots,
  ggbeeswarm,
  ggrepel
)

#Use conda env for reticulate
use_condaenv("ScGwas", required = TRUE)
#colors

#source("/mnt/c/Users/bidos/OneDrive/Posdoc/bepe/Results_Sanger/scripts/autoimmuneSC/Integrated/R/colors.R")

# Source helper functions

#source("/mnt/c/Users/bidos/OneDrive/Posdoc/bepe/Results_Sanger/scripts/autoimmuneSC/Integrated/R/helper_fun.R")

# Network expansion 

#source("/mnt/c/Users/bidos/OneDrive/Posdoc/bepe/Results_Sanger/scripts/autoimmuneSC/Integrated/R/openTarget.R")

#### Windows
source("C:/Users/bidos/OneDrive/Posdoc/bepe/Results_Sanger/scripts/autoimmuneSC/Integrated/R/colors.R")

# Source helper functions

source("C:/Users/bidos/OneDrive/Posdoc/bepe/Results_Sanger/scripts/autoimmuneSC/Integrated/R/helper_fun.R")

# Network expansion 

source("C:/Users/bidos/OneDrive/Posdoc/bepe/Results_Sanger/scripts/autoimmuneSC/Integrated/R/openTarget.R")

```

```{python}
import os,sys
import numpy as np
import pandas as pd
#import drug2cell as d2c
#import scanpy as sc
#import sctk
#import gc
#sys.path.append("/mnt/c/Users/bidos/OneDrive/Posdoc/bepe/Results_Sanger/scripts/autoimmuneSC/AIID_notebooks/")

sys.path.append("C:/Users/bidos/OneDrive/Posdoc/bepe/Results_Sanger/scripts/autoimmuneSC/AIID_notebooks/")

#from inflapy.immunoFunc import *
import gseapy as gp
```

```{r}
#figurePath = "/mnt/g/My Drive/Projects/SCVI_Results/All_Tissue_or_Nonimmune/Subset_Reintegrated_full/Figures/"

figurePath = "G:/My Drive/Projects/SCVI_Results/Immune_compartment_PBMC/Subset_Agosto_2023/Figures/"
```

# Umap Myeloid from tissue

```{r}
obs = read.csv("G:/My Drive/Projects/SCVI_Results/Immune_compartment_PBMC/Subset_Agosto_2023/Milo/Myeloid_From_PBMC_label_transfer_Milo_3K.csv")

umap = read.csv("G:/My Drive/Projects/SCVI_Results/Immune_compartment_PBMC/Subset_Agosto_2023/Milo/Myeloid_From_PBMC_label_transfer_Milo_3K_UMAP.csv")
```

```{r}
unique(umap$Cell_type_scANVI)
```

```{r fig.width= 10, fig.height=7}


umap = umap[umap$Cell_type_scANVI != "CCR7_CDE3",]

umap$Cell_type_scANVI = case_when(
  umap$Cell_type_scANVI == "cMon_1" ~ "Activated cMon",
  umap$Cell_type_scANVI == "cMon_2" ~ "cMon",
  TRUE ~ umap$Cell_type_scANVI
)

umap %>% filter(Cell_type_scANVI != "Unknown") %>% 
  ggplot(aes(x=umap_1, y=umap_2, color = Cell_type_scANVI)) +
  geom_point() +
  theme_bw() +
  scale_colour_manual(values = color_cell_pbmc)
  
```

```{r fig.width= 5, fig.height=4}
plot_umap(
  umap_data = umap,
  cluster = "Cell_type_scANVI",
  umap_1 = "umap_1",
  umap_2 = "umap_2",
  selected_clusters = c(
    "Activated cMon",
    "cMon",
    "Non-cMon"
  ),
  shape.size = 0.5,
  cluster_palette = color_cell_pbmc,
  arrow.length = 3,
  repel_text_size = 3
)



ggsave(
  str_glue(
    "{figurePath}Umap_Milo_myel_From_PBMC_Only_cMon_Non_cMon.svg"
  ),
  width = 5,
  height = 5,
  bg = 'transparent'
)


ggsave(
  str_glue(
    "{figurePath}Umap_Milo_myel_From_PBMC_Only_cMon_Non_cMon.png"
  ),
  width = 5,
  height = 4,
  bg = 'transparent'
)
  
```

```{r}
h5ad_path = 'G:/My Drive/Projects/SCVI_Results/Immune_compartment_PBMC/Subset_Agosto_2023/Milo/'

Nhood_Graph_df = read.csv(str_glue("{h5ad_path}Myeloid_From_PBMC_label_transfer_Milo_3K_reajusted_Nhood_Graph.csv"))

compare_disease_df = read.csv(str_glue("{h5ad_path}Myeloid_From_PBMC_label_transfer_Milo_3K.csv"))

#colnames(compare_disease_df)[1] = "index_cell"

Nhood_Graph_df = compare_disease_df %>% dplyr::select(index_cell, nhood_annotation) %>% unique() %>% 
  inner_join(Nhood_Graph_df[,-7], by = "index_cell")

unique(Nhood_Graph_df$nhood_annotation)

#### Prepare data


Nhood_Graph_df_2 = Nhood_Graph_df[!(Nhood_Graph_df$disease_short %in% c("all_Oligo_JIA", "all_CD_and_spondoarthritis", "all_spondoarthritis")), ]

unique(Nhood_Graph_df_2$disease_short)

Nhood_Graph_df_2$disease_short = str_remove(Nhood_Graph_df_2$disease_short, "all_")

Nhood_Graph_df_2$disease_short = str_replace(Nhood_Graph_df_2$disease_short, "CD", "IBD")

Nhood_Graph_df_2$disease_short = str_replace(Nhood_Graph_df_2$disease_short, "hashimoto", "Hashimoto's thyroiditis")

Nhood_Graph_df_2$disease_short = str_replace(Nhood_Graph_df_2$disease_short, "spondoarthritis", "Spondyloarthritis")

Nhood_Graph_df_2$disease_short = str_replace(Nhood_Graph_df_2$disease_short, "sjo_syndr", "Sjögren Syndrome") 

Nhood_Graph_df_2 = Nhood_Graph_df_2[Nhood_Graph_df_2$nhood_annotation != "CCR7_CDE3", ]

#Nhood_Graph_df_2$disease_short = str_replace(Nhood_Graph_df_2$disease_short, "IBD_and_spondyloarthritis", "IBD_and_Spondyloarthritis")

```

```{r fig.width= 7, fig.height=7}
plot_nhood_graph(
  nhood_data = Nhood_Graph_df_2,
  cluster = "nhood_annotation",
  nhood_1 = "nhood_graph1",
  nhood_2 = "nhood_graph2",
  NHOOD_1_lab = "Nhood \nGraph_1",
  NHOOD_2_lab = "Nhood \nGraph_2",
  selected_clusters = c(
    "Activated cMon",
    "cMon",
    "Non-cMon"
  ),
  shape.size = 1.5,
  repel_text_size = 2,
  cluster_palette = vega_20,
  arrow.length = 3,
  font = "bold",
  ncol = 2
)



ggsave(
  str_glue(
    "{figurePath}Nhood_graph_Milo_myel_From_PBMC_Only_cMon_Non_cMon.svg"
  ),
  width = 7,
  height = 7,
  bg = 'transparent'
)


ggsave(
  str_glue(
    "{figurePath}Nhood_graph_Milo_myel_From_PBMC_Only_cMon_Non_cMon.png"
  ),
  width = 7,
  height = 7,
  bg = 'transparent'
)

```

```{r fig.width= 8, fig.height=8}

gg = plot_nhood_graph(
  nhood_data = Nhood_Graph_df_2,
  cluster = "nhood_annotation",
  nhood_1 = "nhood_graph1",
  nhood_2 = "nhood_graph2",
  NHOOD_1_lab = "Nhood \nGraph_1",
  NHOOD_2_lab = "Nhood \nGraph_2",
  selected_clusters = c(
    "Activated cMon",
    "cMon",
    "Non-cMon"
  ),
  shape.size = 1.5,
  repel_text_size = 2,
  cluster_palette = vega_20,
  arrow.length = 3,
  font = "bold",
  FC = TRUE,
  logFC = "logFC",
  FC_dir = "enriched_depleted",
  ncol = 2
)

gg

ggsave(
  str_glue(
    "{figurePath}Nhood_graph_facet_Milo_myel_From_PBMC_Only_cMon_Non_cMon.svg"
  ),
  width = 8,
  height = 8,
  bg = 'transparent'
)


ggsave(
  str_glue(
    "{figurePath}Nhood_graph_facet_Milo_myel_From_PBMC_Only_cMon_Non_cMon.png"
  ),
  width = 8,
  height = 8,
  bg = 'transparent'
)

```

# Umap Myeloid from PBMC

```{r}
obs = read.csv("G:/My Drive/Projects/SCVI_Results/Immune_compartment_PBMC/Subset_Agosto_2023/Milo/Myeloid_From_PBMC_label_transfer_Milo_3K_UMAP.csv")

obs = obs[obs$Cell_type_scANVI != "CCR7_CDE3",]

obs$Cell_type_scANVI = case_when(
  obs$Cell_type_scANVI == "cMon_1" ~ "Activated cMon",
  obs$Cell_type_scANVI == "cMon_2" ~ "cMon",
  TRUE ~ obs$Cell_type_scANVI
)

```

```{r fig.width= 10, fig.height=7}


plot_umap(
  umap_data = obs[umap$Cell_type_scANVI!="Unknown",],
  cluster = "Cell_type_scANVI",
  umap_1 = "umap_1",
  umap_2 = "umap_2",
  selected_clusters = "all",
  shape.size = 0.5,
  cluster_palette = color_cell_pbmc,
  arrow.length = 5,
  axis.lab.size = 6,
  repel_text_size = 7,
  repel = "label",
  cust.alpha = 0.7
)


  
```

```{r}
ggsave(
  str_glue(
    "{figurePath}Umap_Milo_myel_From_PBMC.png"
  ),
  width = 10,
  height = 7,
  bg = 'transparent'
) 

```

```{r}
umap$disease_short_2 = ifelse(umap$disease_short=="Healthy", "Healthy", "Diseases") %>% as.factor()

table(umap$disease_short_2)
```

```{r fig.width= 10, fig.height=7}


plot_umap(
  umap_data = umap[umap$Cell_type_scANVI!="Unknown",],
  cluster = "disease_short_2",
  umap_1 = "umap_1",
  umap_2 = "umap_2",
  selected_clusters = "all",
  shape.size = 0.5,
  cluster_palette = c(Healthy = "#ce9cf9", Diseases = "#ccc1cc"),
  arrow.length = 3,
  repel_text_size = 4,
  repel = "label",
  cust.alpha = 0.7,
  legend.position = "right"
    
) 
  
  
```

## Heatmap

```{r fig.width=11, fig.height=18}
#| fig-width: 25
#| fig-height: 100


cel_nh = unique(test_adata_$Cell_type_scANVI)


n_top = 25

test_adata_sub = test_adata_[, test_adata_$Cell_type_scANVI %in% c("Activated cMon", "cMon")]

test_adata_sub$disease_short = str_remove(test_adata_sub$disease_short, "all_")

test_adata_sub$disease_short = str_replace(test_adata_sub$disease_short, "CD", "IBD")

test_adata_sub$disease_short = str_replace(test_adata_sub$disease_short, "hashimoto", "Hashimoto's thyroiditis")

test_adata_sub$disease_short = str_replace(test_adata_sub$disease_short, "spondoarthritis", "Spondyloarthritis")

test_adata_sub$disease_short = str_replace(test_adata_sub$disease_short, "sjo_syndr", "Sjögren Syndrome") 

Nhood_Graph_df_2 = Nhood_Graph_df_2[Nhood_Graph_df_2$nhood_annotation != "CCR7_CDE3", ]

#test_adata_sub = test_adata_[, test_adata_$Cell_type_scANVI %in% c("Intermediate_macrophage", "Mac_MERTK_hi_TREM2_low", "Mac_NUPR1_TREM2_hi", #"Mac_S100A8_prod", "Mo_Mac_CX3CR1", "Mo_Mac_LYVE1_plus")]

test_adata_prep = prep_de_data(depl_ = "", enrch_ = "", test_adata = test_adata_sub, nhood = FALSE, hvgs = FALSE, cel_of_int_vs_rest = T, cell_type = "Activated cMon")

test_adata_prep$Cell_type_scANVI %>% unique()
test_adata_prep$disease_short %>% unique()

test_adata_prep$disease_short = factor(test_adata_prep$disease_short, levels = c("Healthy", sort(as.character(
  unique(test_adata_prep$disease_short[!(test_adata_prep$disease_short %in% c("Healthy"))])
))))
  
test_adata_prep$disease_short %>% unique()

gsea_net_heat = rbind(
  data.frame(
    Term = gsea_MSigDB_Hallmark_2020$Term[1],
    symbol = str_split_1(gsea_MSigDB_Hallmark_2020$leading_edge[1], pattern = ",")
  ),
  data.frame(
    Term = gsea_MSigDB_Hallmark_2020$Term[2],
    symbol = str_split_1(gsea_MSigDB_Hallmark_2020$leading_edge[2], pattern = ",")
  )
)


gsea_net_heat$value = 1

gsea_net_heat = pivot_wider(gsea_net_heat, names_from = Term, values_from = value, values_fill = 0)

gsea_net_heat = tibble::column_to_rownames(gsea_net_heat, var="symbol")

colnames(gsea_net_heat) = str_replace(colnames(gsea_net_heat), "Response", "\nResponse")

plot_heatmap_wout_bar(
  test_adata = test_adata_prep[,test_adata_prep$disease_short!="Healthy"],
  cel.selected = "Activated cMon",
  selected_gene = rownames(gsea_net_heat),
  gsea_net_heat = gsea_net_heat,
  ref.vs.other = FALSE,
  n_top = 15,
  aggregate = TRUE,
  show_column_names = TRUE,
  aggr_fun = "mean",
  col_pal = vega_20,
  test.column = "Cell_type_scANVI",
  column.label = "disease_short",
  col_test = c("grey", "grey50"),
  scale = TRUE,
  remove_inf = TRUE,
  cluster.col = FALSE,
  labels_annot_bar = TRUE,
  label.only.disease = FALSE,
  figure_Path = str_glue("{figurePath}Heatmap_cMon_1_vs_cMon_1_only_disease"),
  save = F,
  fig.width = 11,
  fig.height = 18,
  font = 25,
  path.col.font = 20,
  title.font = 18,
  title.face = "bold",
  fontface = "bold",
  grid_width = 15,
  legend_h = 10,
  legend_w = 2,
  grid_width1 = 2,
  grid_height1 = 2,
  title_g = 10, broadcell = "macrophages",
  grid_width_row_annot = 8, 
  rowannot = T, path_title = "Pathways",
  column.name.col = "grey20"
)


```
